### PR TITLE
Fix for getProducts returning Success when no products are found

### PR DESCRIPTION
**Pull request by mkral**

### CODE REVIEW

**Comment by bennyguitar** [comment]
Cocoapods uses semantic versioning which is basically x.x.x, so you should commit the podspec again to be 1.2.1 for this fix. I'll merge this in after that's done.

**Comment by mkral** [comment]
ok thanks, didn't know that.

**Comment by bennyguitar** [comment]
Yeah no problem, I figured letting you know on here would help for any future Cocoapod development you do. Thanks for helping out on my repository!

**Comment by mkral** [comment]
No worries, I've been using it a lot!

**Pull request merged**
